CREATE DATABASE portfolio;
USE portfolio;

CREATE TABLE form(
id INT AUTO_INCREMENT PRIMARY KEY,
nama VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
pesan VARCHAR(100) NOT NULL
);

SELECT * FROM form;
TRUNCATE TABLE form;
ALTER TABLE form AUTO_INCREMENT = 1;

CREATE TABLE pengguna(
id INT AUTO_INCREMENT PRIMARY KEY,
nama VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
telp VARCHAR(50) NOT NULL,
sandi VARCHAR(100) NOT NULL
);

SELECT * FROM pengguna;


